import { AI_STATES, INTAKE_STEPS, OFFICIAL_GAS_ENDPOINT, benefitAppearsInCategory, categoryBenefits, comparePolicy, createDeviceTransferPointer, coverageTotals, exportUserLayer, loadInsuredPersonData, loadOfficialRegistry, matchProduct, normalizeSearchName, openUserDatabase, queryByIndex, queryIndexPrefix, resolveProductMatch, saveUserLayerMutation } from './crm-core.js';

const $ = (id) => document.getElementById(id); const modal = $('modal');
const state = { db: null, registry: null, households: [], household: null, people: [], insuredPerson: null, selectedData: { roles: [], policies: [], benefits: [], values: [] }, perception: '', activeCategory: 'medical', categoryPerceptions: {}, priority: '', sessionStep: 0, dataFileHandle: null, fileSync: 'pending', officialSource: 'built-in-fallback' };
const steps = ['perception', 'coverage', 'resources', 'retirement', 'reservoirs', 'review', 'presentation'];
function showModal(title, body, action = '') { $('modalBody').innerHTML = `<h2>${title}</h2><p>${body}</p>${action}`; modal.showModal(); }
function personRecord(householdId, name, relationship = '本人') { return { id: crypto.randomUUID(), householdId, name, relationship, createdAt: new Date().toISOString() }; }
async function saveMutation(storeName, value) { const result = await saveUserLayerMutation({ db: state.db, storeName, value, fileHandle: state.dataFileHandle }); if (result.fileSync === 'unavailable') state.dataFileHandle = null; state.fileSync = result.fileSync; $('storageStatus').textContent = result.fileSync === 'synced' ? '本機＋檔案已同步' : result.fileSync === 'unavailable' ? '本機已保存 · 檔案待重連' : '本機已保存 · 檔案待同步'; return result; }
function refreshCustomerOptions() { const select = $('customerSelect'); select.innerHTML = state.households.length ? '<option value="">請選擇搜尋結果</option>' : '<option value="">沒有符合的本機客戶</option>'; for (const household of state.households) select.add(new Option(household.displayName, household.id)); const empty = state.households.length === 0; $('customerEmpty').hidden = Boolean($('customerSearch').value) || !empty; $('customerFields').hidden = false; for (const id of ['manualPolicyBtn', 'aiPolicyBtn']) $(id).disabled = !state.household; }
async function searchHouseholds(event) { const query = normalizeSearchName(event.target.value); state.households = query.length >= 1 ? await queryIndexPrefix(state.db, 'households', 'bySearchName', query, 50) : []; state.household = null; state.insuredPerson = null; refreshCustomerOptions(); }
async function loadHouseholds() { state.households = []; $('customerFields').hidden = false; refreshCustomerOptions(); }
async function addCustomer() { const name = window.prompt('客戶姓名 / Customer name（只會保存在本機）'); if (!name?.trim()) return; const household = { id: crypto.randomUUID(), displayName: name.trim(), searchName: normalizeSearchName(name), createdAt: new Date().toISOString() }; const person = personRecord(household.id, name.trim()); household.primaryPersonId = person.id; await saveMutation('households', household); await saveMutation('people', person); state.households.push(household); refreshCustomerOptions(); $('customerSearch').value = household.searchName; $('customerSelect').value = household.id; await selectHousehold({ target: $('customerSelect') }); await requestDataFileLocation(); }
async function selectHousehold(event) { const id = event.target.value; state.household = state.households.find((item) => item.id === id) || null; state.people = state.household ? await queryByIndex(state.db, 'people', 'byHouseholdId', state.household.id) : []; const insured = $('insuredSelect'); insured.innerHTML = state.people.length ? '<option value="">請選擇被保人</option>' : '<option value="">沒有可選被保人</option>'; state.people.forEach((person) => insured.add(new Option(`${person.name} · ${person.relationship}`, person.id))); insured.disabled = !state.people.length; $('manualPolicyBtn').disabled = !state.household; $('aiPolicyBtn').disabled = !state.household; }
function selectInsured(event) { state.insuredPerson = state.people.find((person) => person.id === event.target.value) || null; $('startReviewBtn').disabled = !(state.household && state.insuredPerson); }
async function requestDataFileLocation() { if (state.dataFileHandle) return; localStorage.setItem('ava-crm-file-location-requested', 'true'); if (!window.showSaveFilePicker) { state.fileSync = 'unavailable'; showModal('本機資料已保存', 'IndexedDB 已保存客戶資料。此瀏覽器未提供支援的系統檔案選擇器；檔案同步：BLOCKED，保留本機安全 fallback。'); return; } try { state.dataFileHandle = await window.showSaveFilePicker({ suggestedName: 'ava-crm-data.json', types: [{ description: 'AVA-CRM data', accept: { 'application/json': ['.json'] } }] }); const synced = await syncDataFile(); showModal(synced ? '資料檔案已設定' : '檔案同步待重連', synced ? '已建立包含結構化 User Layer 的 AVA-CRM 資料檔。IndexedDB 仍是操作資料庫；背景持久寫入能力按平台驗證，不會默認成功。' : 'IndexedDB 已保存資料，但目前無法寫入檔案；資料安全保留，請稍後按「連接資料檔」重試。'); } catch (error) { if (error?.name !== 'AbortError') { state.fileSync = 'unavailable'; showModal('仍可使用本機資料', '你取消了檔案位置選擇；資料仍在 IndexedDB，未上傳。'); } } }
async function syncDataFile() { if (!state.dataFileHandle) return false; try { const writable = await state.dataFileHandle.createWritable(); await writable.write(JSON.stringify(await exportUserLayer(state.db), null, 2)); await writable.close(); state.fileSync = 'synced'; $('storageStatus').textContent = '本機＋檔案已同步'; return true; } catch { state.dataFileHandle = null; state.fileSync = 'unavailable'; $('storageStatus').textContent = '本機已保存 · 檔案待重連'; return false; } }

function renderCategory(category) { state.activeCategory = category; const copy = { medical: ['醫療保障', '你期望醫療保障解決什麼？再對照實際的住院醫療、手術保障、住院現金及意外醫療。', '✚', ['住院、手術、保費？', '我想知道可否報銷？']], critical: ['危疾保障', '你期望危疾保障如何幫到你？再對照賠償、multiple payout 與 continuation payout。', '◇', ['一次賠償、持續支援？', '我想知道可否多次賠償？']], life: ['人壽保障', '你期望為誰留下什麼保障？再對照人壽保障與受保人角色。', '◯', ['家庭保障額？', '我想知道保障到幾時？']], accident: ['意外保障', '你期望意外保障處理什麼情況？再對照意外身故、傷殘與意外醫療。', '＋', ['意外醫療、身故？', '我想知道發生意外怎樣？']] }[category]; $('coveragePanelTitle').textContent = copy[0]; $('coveragePanelCopy').textContent = copy[1]; document.querySelector('.category-icon').textContent = copy[2]; $('categoryExpectation').innerHTML = `<strong>你最想先了解：</strong><div class="expectation-options">${copy[3].map((option) => `<button class="topic-pill category-expectation-choice" data-value="${option}">${option}</button>`).join('')}</div>`; $('categoryExpectation').querySelectorAll('button').forEach((button) => { button.onclick = () => { state.categoryPerceptions[category] = button.dataset.value; button.classList.add('is-selected'); }; }); const benefits = categoryBenefits(state.selectedData.benefits, category); const list = $('coverageBenefits'); list.innerHTML = benefits.length ? benefits.map((benefit) => `<div class="benefit-row"><strong>${benefit.benefitType || benefit.benefitCategory}</strong><span>${benefit.amount ?? benefit.limit ?? '待確認'} ${benefit.unit || ''}</span><small>${benefit.benefitForm || '保障形式待確認'}${(benefit.presentationTags || []).includes('medical') && benefit.primaryCategory === 'accident' ? ' · 意外醫療跨類別展示，唯一記錄' : ''}</small></div>`).join('') + `<small class="coverage-total">本類別顯示總額：${coverageTotals(benefits, category)}（只按唯一 Benefit ID 計算）</small>` : '<span class="empty-number">—</span><span>此被保人尚未有已確認的本類別 Benefit</span>'; }
function renderReview() { const list = $('policyReviewList'); list.innerHTML = state.selectedData.policies.length ? state.selectedData.policies.map((policy) => `<button class="policy-review-row" data-policy-id="${policy.id}"><strong>${policy.insurer || '來源待確認'} · ${policy.productName || '產品待確認'}</strong><span>保障 / 價值：${policy.coverageValue ?? '待確認'} · 保費：${policy.premium ?? '待確認'} · 繳費期：${policy.paymentTerm ?? '待確認'}</span><small>保障期：${policy.coverageTerm ?? '待確認'} · 選擇後查看 Level 3</small></button>`).join('') : '<p class="ava-support">此被保人尚未有已確認保單資料。</p>'; list.querySelectorAll('[data-policy-id]').forEach((button) => { button.onclick = () => showPolicyInspect(state.selectedData.policies.find((policy) => policy.id === button.dataset.policyId)); }); }
function renderResources() { const values = state.selectedData.values; const byType = (type) => values.filter((value) => value.valueType === type).reduce((total, value) => total + (Number.isFinite(Number(value.amount)) ? Number(value.amount) : 0), 0); $('resourceCurrent').textContent = values.length ? String(byType('current_policy_cash_value') || byType('fund_current_value') || '待確認') : '未有'; $('resourceGuaranteed').textContent = values.some((value) => value.valueType === 'guaranteed_value') ? String(byType('guaranteed_value')) : '未有'; $('resourceNonGuaranteed').textContent = values.some((value) => value.valueType === 'non_guaranteed_value') ? String(byType('non_guaranteed_value')) : '未有'; }
async function startSession() { state.sessionStep = 0; state.selectedData = await loadInsuredPersonData(state.db, state.insuredPerson.id); $('agentHome').hidden = true; $('agentHeader').classList.add('session-mode'); $('customerSession').hidden = false; $('sessionTitle').textContent = `${state.insuredPerson.name} 的保障理解`; document.body.dataset.avaMode = 'presentation'; renderCategory('medical'); renderReview(); renderResources(); renderStep(); }
function endSession() { state.sessionStep = 0; state.perception = ''; state.priority = ''; state.selectedData = { roles: [], policies: [], benefits: [], values: [] }; $('customerSession').hidden = true; $('agentHome').hidden = false; $('agentHeader').classList.remove('session-mode'); document.body.dataset.avaMode = 'use'; }
function renderStep() { document.querySelectorAll('.session-step').forEach((element) => { element.hidden = element.dataset.step !== steps[state.sessionStep]; }); $('sessionProgressFill').style.width = `${((state.sessionStep + 1) / steps.length) * 100}%`; document.querySelector('.session-progress').setAttribute('aria-valuenow', String(state.sessionStep + 1)); if (steps[state.sessionStep] === 'presentation') { $('summaryPerception').textContent = state.perception || '—'; $('summaryPriority').textContent = state.priority || '—'; } }
function nextStep() { if (state.sessionStep < steps.length - 1) { state.sessionStep += 1; renderStep(); } }
function previousStep() { if (state.sessionStep > 0) { state.sessionStep -= 1; renderStep(); } }
function choosePerception(event) { document.querySelectorAll('.perception-option').forEach((button) => button.setAttribute('aria-pressed', String(button === event.currentTarget))); state.perception = event.currentTarget.dataset.perception; $('perceptionNext').disabled = false; }
function choosePriority(event) { state.priority = event.currentTarget.dataset.value; document.querySelectorAll('.priority-choice').forEach((button) => button.classList.toggle('is-selected', button === event.currentTarget)); }
function selectCategory(event) { document.querySelectorAll('.category-tab').forEach((tab) => { const active = tab === event.currentTarget; tab.classList.toggle('is-active', active); tab.setAttribute('aria-selected', String(active)); }); renderCategory(event.currentTarget.dataset.category); }
function showPolicyInspect(policy) { if (!policy) return; const masked = policy.policyNumber ? `${String(policy.policyNumber).slice(0, 2)}••••${String(policy.policyNumber).slice(-2)}` : '未有保單號碼'; const benefits = state.selectedData.benefits.filter((benefit) => benefit.policyId === policy.id); showModal(`Level 3 · ${policy.productName || '保單'}`, `<strong>保單號碼：</strong>${masked}<br><strong>保險公司：</strong>${policy.insurer || '待確認'}<br><strong>Coverage term：</strong>${policy.coverageTerm || '待確認'}<br><strong>Benefits：</strong>${benefits.length ? benefits.map((benefit) => benefit.benefitType || benefit.benefitCategory).join('、') : '待確認'}`, '<p class="blocked-note">完整 Inspect 只顯示 confirmed structured fields；原始 PDF/image 不會保存亦不影響資料完整度。</p>'); }

async function aiIntake() { const registryProducts = state.registry?.['產品資料'] || []; const registryContract = resolveProductMatch(registryProducts, {}); showModal('AI 加入保單', `上載前請注意：PDF / 圖片只作今次閱讀，最多 10 個 upload items；原始檔案不會保存。AI 輸出一定先是 draft / needs_confirmation，確認後才可寫入正式 CRM。Official Product Registry：${state.officialSource}；正式 extraction 後會以 Insurer + Product Name + Product Version 匹配，exact match 才可自動帶入 verified features，candidate / no match 必須確認。`, '<label class="ava-button ava-button--secondary" for="policyFiles">選擇 PDF / 圖片</label><input id="policyFiles" type="file" accept="application/pdf,image/*" multiple hidden><p class="ava-support">流程：Upload → Document Understanding → Policy Grouping → Policy Extraction → Product Matching → Feature Matching → Coverage Classification → Conflict / Missing Data Detection → Human Confirmation → Save → Delete temporary source</p>'); $('policyFiles').onchange = async (event) => { const files = [...event.target.files]; if (files.length > 10) return showModal('檔案數量超過上限', '每批最多 10 個上載項目。'); const draft = { id: crypto.randomUUID(), householdId: state.household.id, insuredPersonId: state.insuredPerson?.id || '', state: AI_STATES[0], registrySource: state.officialSource, registryMatchContract: registryContract.status, pipeline: INTAKE_STEPS.map((name) => ({ name, status: name === 'Upload' ? 'complete' : 'blocked' })), sourceItems: files.map((file) => ({ name: file.name, type: file.type, size: file.size })), backendStatus: 'BLOCKED', backendMessage: '實際 AI Document Understanding backend 尚未接通；沒有假造 extraction 結果。', createdAt: new Date().toISOString() }; await saveMutation('intakeDrafts', draft); showModal('AI intake 已建立草稿', `狀態：${draft.state} → needs_confirmation → confirmed。Backend extraction：BLOCKED；未寫入 formal policy，臨時原始檔案只存在此次 reading session，已由瀏覽器 file input 釋放。`, '<button class="ava-button ava-button--secondary" id="viewIntakeContract">查看 Intake Contract</button>'); $('viewIntakeContract').onclick = () => showModal('Human Confirmation 必須先發生', '待 backend 可用後，系統會接收 Policy、Benefits、Product identity/version、Extracted features、Confidence、Conflicts，再用 Official Product Registry resolver：exact → verified；candidate → confirmation；none → AI features needs_confirmation。'); }; }
function manualPolicy() { showModal('手動加入保單', 'Manual policy entry contract：Policy、Policy Roles、Benefits 分開保存；policyholder 與 insured person 可為不同 People。正式保存前仍需確認。'); }
function deviceTransfer() { showModal('裝置轉移', 'Generate QR Code / Scan QR Code 的 UI contract 已保留，但安全 transfer backend 尚未由 AVA Platform 提供，因此實際 transfer：BLOCKED。QR 絕不放入 raw customer data。', `<div class="transfer-actions"><button class="ava-button ava-button--secondary" id="generateQrBtn">Generate QR Code</button><button class="ava-button ava-button--secondary" id="scanQrBtn">Scan QR Code</button></div><p class="blocked-note">Pointer contract（不含客戶資料）：${createDeviceTransferPointer()}</p>`); $('generateQrBtn').onclick = () => showModal('Generate QR Code · BLOCKED', '待 Mother Platform secure transfer service 接通；目前不產生假 QR。'); $('scanQrBtn').onclick = () => showModal('Scan QR Code · BLOCKED', '待 Mother Platform secure transfer service 接通；目前不讀取未知資料。'); }

$('modalClose').onclick = () => modal.close(); $('addCustomerBtn').onclick = addCustomer; $('customerSearch').oninput = searchHouseholds; $('customerSelect').onchange = selectHousehold; $('insuredSelect').onchange = selectInsured; $('aiPolicyBtn').onclick = aiIntake; $('manualPolicyBtn').onclick = manualPolicy; $('deviceTransferBtn').onclick = deviceTransfer; $('deviceTransferFooter').onclick = deviceTransfer; $('fileReconnectBtn').onclick = requestDataFileLocation; $('startReviewBtn').onclick = startSession; $('endSessionBtn').onclick = endSession; $('perceptionNext').onclick = nextStep; $('presentationBack').onclick = () => { state.sessionStep = 5; renderStep(); };
document.querySelectorAll('.session-next').forEach((button) => button.addEventListener('click', nextStep)); document.querySelectorAll('.session-back').forEach((button) => button.addEventListener('click', previousStep)); document.querySelectorAll('.perception-option').forEach((button) => button.addEventListener('click', choosePerception)); document.querySelectorAll('.priority-choice').forEach((button) => button.addEventListener('click', choosePriority)); document.querySelectorAll('.category-tab').forEach((button) => button.addEventListener('click', selectCategory)); document.querySelectorAll('.retirement-choice').forEach((button) => button.addEventListener('click', (event) => event.currentTarget.classList.toggle('is-selected')));
openUserDatabase().then(async (db) => { state.db = db; $('storageStatus').textContent = db ? '本機已就緒' : 'IndexedDB：BLOCKED'; await loadHouseholds(); }).catch(() => { $('storageStatus').textContent = 'IndexedDB：BLOCKED'; });
loadOfficialRegistry().then((result) => { state.registry = result.payload; state.officialSource = result.source; document.body.dataset.officialSource = result.source; }).catch(() => { document.body.dataset.officialSource = 'built-in-fallback'; });
window.addEventListener('beforeunload', () => state.db?.close());
console.info('AVA-CRM official configuration endpoint (read-only):', OFFICIAL_GAS_ENDPOINT, 'Product matching ready:', typeof matchProduct === 'function');
