export const OFFICIAL_GAS_ENDPOINT = 'https://script.google.com/macros/s/AKfycbyvGzKK5v9VEXyTeCmGUKhnVXgO6eh7Hg6FDEfwEIfsd58SCtPdNQvW21wTp9J5FfAX/exec';
export const DB_NAME = 'ava-crm-user-layer';
export const DB_VERSION = 3;
export const AI_STATES = ['draft', 'needs_confirmation', 'confirmed'];
export const INTAKE_STEPS = ['Upload', 'Document Understanding', 'Policy Grouping', 'Policy Extraction', 'Product Matching', 'Feature Matching', 'Coverage Classification', 'Conflict / Missing Data Detection', 'Human Confirmation', 'Save structured data', 'Delete temporary source'];
export const POLICY_COMPARE_FIELDS = ['insurer', 'productName', 'productVersion', 'policyNumber', 'coverageTerm', 'premium', 'paymentTerm', 'paymentFrequency', 'currency', 'status', 'benefits'];

export function normalizeSearchName(value = '') { return String(value).normalize('NFKC').trim().toLocaleLowerCase(); }
export function createBenefit(input = {}) { return { id: input.id || crypto.randomUUID(), policyId: input.policyId || '', insuredPersonId: input.insuredPersonId || '', primaryCategory: input.primaryCategory || 'medical', benefitCategory: input.benefitCategory || input.primaryCategory || 'medical', presentationTags: input.presentationTags || [], benefitType: input.benefitType || '', amount: input.amount ?? null, limit: input.limit ?? null, currency: input.currency || '', unit: input.unit || '', benefitForm: input.benefitForm || '', metadata: input.metadata || {}, createdAt: input.createdAt || new Date().toISOString() }; }
export function dedupeBenefits(benefits) { const unique = new Map(); for (const benefit of benefits) unique.set(benefit.id, benefit); return [...unique.values()]; }
export function benefitAppearsInCategory(benefit, category) { return benefit.primaryCategory === category || (benefit.presentationTags || []).includes(category) || benefit.benefitCategory === category; }
export function categoryBenefits(benefits, category) { return dedupeBenefits(benefits.filter((benefit) => benefitAppearsInCategory(benefit, category))); }
export function coverageTotals(benefits, category) {
  const eligible = categoryBenefits(benefits, category);
  if (!eligible.length) return null;
  const aggregations = eligible.map((benefit) => benefit.metadata?.aggregation);
  const first = aggregations[0];
  if (!first?.allowed || !first.type || !first.definition || !first.semanticBasis || !eligible[0].currency || !eligible[0].unit || !eligible[0].benefitForm) return null;
  if (eligible.some((benefit, index) => {
    const aggregation = aggregations[index];
    return !aggregation?.allowed || aggregation.type !== first.type || aggregation.definition !== first.definition || aggregation.semanticBasis !== first.semanticBasis || benefit.currency !== eligible[0].currency || benefit.unit !== eligible[0].unit || benefit.benefitForm !== eligible[0].benefitForm;
  })) return null;
  const amounts = eligible.map((benefit) => Number(benefit.amount));
  return amounts.every(Number.isFinite) ? amounts.reduce((total, amount) => total + amount, 0) : null;
}
export function comparePolicy(existing = {}, extracted = {}) { return POLICY_COMPARE_FIELDS.filter((field) => JSON.stringify(existing[field] ?? null) !== JSON.stringify(extracted[field] ?? null)).map((field) => ({ field, existing: existing[field] ?? null, extracted: extracted[field] ?? null })); }
function hasConfirmedCompatibleVersion(product, version) {
  const n = normalizeSearchName;
  if (!version) return false;
  if (n(product.productVersion) === version) return true;
  const compatibleVersions = product.compatibleProductVersions || product.productVersionAliases || product.metadata?.compatibleProductVersions || [];
  return compatibleVersions.some((compatibleVersion) => n(compatibleVersion) === version);
}
export function matchProduct(products = [], query = {}) { const n = normalizeSearchName; const insurer = n(query.insurer); const product = n(query.productName); const version = n(query.productVersion); const exact = products.find((item) => n(item.insurer) === insurer && n(item.productName) === product && hasConfirmedCompatibleVersion(item, version)); if (exact) return { status: 'exact', product: exact, requiresConfirmation: false }; const candidates = products.filter((item) => n(item.insurer) === insurer && product && meaningfulProductSimilarity(n(item.productName), product)); return candidates.length ? { status: 'candidate', candidates, requiresConfirmation: true } : { status: 'none', candidates: [], requiresConfirmation: true }; }
export function meaningfulProductSimilarity(left, right) { if (!left || !right) return false; if (left === right || left.includes(right) || right.includes(left)) return true; const leftTokens = new Set(left.split(/[\s·•丨|，,()（）-]+/).filter(Boolean)); const rightTokens = new Set(right.split(/[\s·•丨|，,()（）-]+/).filter(Boolean)); return [...leftTokens].some((token) => token.length >= 2 && rightTokens.has(token)); }
export function resolveProductMatch(products = [], extracted = {}) { const result = matchProduct(products, extracted); if (result.status === 'exact') return { ...result, verifiedFeatures: result.product.features || [], customerExplanations: result.product.customerExplanations || [] }; if (result.status === 'candidate') return { ...result, candidateFeatures: [], message: 'Candidate match requires User confirmation.' }; return { ...result, candidateFeatures: extracted.features || [], message: 'No verified registry match; extracted features remain needs_confirmation.' }; }
export function createDeviceTransferPointer() { return `ava-crm-transfer:${crypto.randomUUID()}`; }
export function emptyOfficialRegistry() { return { '保障分類': [], '產品資料': [], 'Review問題': [], '頁面設定': [], '系統設定': [] }; }

export const STORE_DEFINITIONS = { households: [['byCreatedAt', 'createdAt'], ['bySearchName', 'searchName']], people: [['byHouseholdId', 'householdId']], policies: [['byHouseholdId', 'householdId'], ['byPolicyHolderId', 'policyHolderId']], policyRoles: [['byPolicyId', 'policyId'], ['byPersonId', 'personId'], ['byPolicyHolderId', 'policyHolderId'], ['byInsuredPersonId', 'insuredPersonId']], benefits: [['byPolicyId', 'policyId'], ['byPrimaryCategory', 'primaryCategory'], ['byBenefitCategory', 'benefitCategory'], ['byInsuredPersonId', 'insuredPersonId']], policyValues: [['byPolicyId', 'policyId'], ['byInsuredPersonId', 'insuredPersonId'], ['byValueType', 'valueType']], reviews: [['byHouseholdId', 'householdId'], ['byInsuredPersonId', 'insuredPersonId']], intakeDrafts: [['byHouseholdId', 'householdId'], ['byStatus', 'status']], settings: [['byKey', 'key']] };
export const STORE_NAMES = Object.keys(STORE_DEFINITIONS);

export async function openUserDatabase() { if (!('indexedDB' in globalThis)) return null; return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, DB_VERSION); request.onupgradeneeded = () => { const db = request.result; for (const [storeName, indexes] of Object.entries(STORE_DEFINITIONS)) { const store = db.objectStoreNames.contains(storeName) ? request.transaction.objectStore(storeName) : db.createObjectStore(storeName, { keyPath: 'id' }); for (const [name, keyPath] of indexes) if (!store.indexNames.contains(name)) store.createIndex(name, keyPath, { unique: false }); } }; request.onsuccess = () => { const db = request.result; const migration = db.transaction('households', 'readwrite'); const cursorRequest = migration.objectStore('households').openCursor(); cursorRequest.onsuccess = () => { const cursor = cursorRequest.result; if (!cursor) return; const value = cursor.value; const searchName = normalizeSearchName(value.searchName || value.displayName); if (value.searchName !== searchName) cursor.update({ ...value, searchName }); cursor.continue(); }; resolve(db); }; request.onerror = () => reject(request.error); }); }
export async function saveLocal(db, storeName, value) { if (!db) return false; return new Promise((resolve, reject) => { const tx = db.transaction(storeName, 'readwrite'); tx.objectStore(storeName).put(value); tx.oncomplete = () => resolve(true); tx.onerror = () => reject(tx.error); }); }
export async function queryByIndex(db, storeName, indexName, value) { if (!db) return []; return new Promise((resolve, reject) => { const tx = db.transaction(storeName, 'readonly'); const request = tx.objectStore(storeName).index(indexName).getAll(IDBKeyRange.only(value)); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
export async function getById(db, storeName, id) { if (!db) return null; return new Promise((resolve, reject) => { const request = db.transaction(storeName, 'readonly').objectStore(storeName).get(id); request.onsuccess = () => resolve(request.result || null); request.onerror = () => reject(request.error); }); }
export async function queryIndexPrefix(db, storeName, indexName, prefix, limit = 50) { if (!db) return []; return new Promise((resolve, reject) => { const output = []; const tx = db.transaction(storeName, 'readonly'); const request = tx.objectStore(storeName).index(indexName).openCursor(IDBKeyRange.bound(prefix, `${prefix}\uffff`)); request.onsuccess = () => { const cursor = request.result; if (!cursor || output.length >= limit) return resolve(output); output.push(cursor.value); cursor.continue(); }; request.onerror = () => reject(request.error); }); }
export function relevantPolicyIds(roles = [], insuredPersonId) { return [...new Set(roles.filter((role) => role.insuredPersonId === insuredPersonId).map((role) => role.policyId).filter(Boolean))]; }
export async function loadInsuredPersonData(db, insuredPersonId) { const roles = await queryByIndex(db, 'policyRoles', 'byInsuredPersonId', insuredPersonId); const policyIds = relevantPolicyIds(roles, insuredPersonId); const policies = (await Promise.all(policyIds.map((policyId) => getById(db, 'policies', policyId)))).filter(Boolean); const benefits = (await Promise.all(policyIds.map((policyId) => queryByIndex(db, 'benefits', 'byPolicyId', policyId)))).flat(); const values = (await Promise.all(policyIds.map((policyId) => queryByIndex(db, 'policyValues', 'byPolicyId', policyId)))).flat(); return { roles, policies, benefits: dedupeBenefits(benefits), values }; }
export async function exportUserLayer(db) { if (!db) return null; const data = {}; for (const storeName of STORE_NAMES) data[storeName] = await new Promise((resolve, reject) => { const request = db.transaction(storeName, 'readonly').objectStore(storeName).getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); return { app: 'AVA-CRM', schemaVersion: DB_VERSION, exportedAt: new Date().toISOString(), data }; }
export async function saveUserLayerMutation({ db, storeName, value, fileHandle, exportFn = exportUserLayer, saveFn = saveLocal }) { const saved = await saveFn(db, storeName, value); if (!saved) return { saved: false, fileSync: 'unavailable' }; if (!fileHandle) return { saved: true, fileSync: 'pending' }; try { const writable = await fileHandle.createWritable(); await writable.write(JSON.stringify(await exportFn(db), null, 2)); await writable.close(); return { saved: true, fileSync: 'synced' }; } catch { return { saved: true, fileSync: 'unavailable' }; } }
export async function loadOfficialRegistry(fetchImpl = fetch, storage = localStorage) { const cacheKey = 'ava-crm-official-registry-v3'; try { const response = await fetchImpl(OFFICIAL_GAS_ENDPOINT, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error(`Official registry request failed: ${response.status}`); const payload = await response.json(); storage.setItem(cacheKey, JSON.stringify({ savedAt: new Date().toISOString(), payload })); return { source: 'official', payload }; } catch { try { const cached = JSON.parse(storage.getItem(cacheKey) || 'null'); if (cached?.payload) return { source: 'official-cache', payload: cached.payload }; } catch { /* safe fallback */ } return { source: 'built-in-fallback', payload: emptyOfficialRegistry() }; } }
